# Generated by Django 5.2.5 on 2025-10-26 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('target_hostname', models.CharField(max_length=200)),
                ('target_os', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('recon', 'Reconnaissance'), ('analysis', 'AI Analysis'), ('attack', 'Attack Simulation'), ('reporting', 'Generating Report'), ('complete', 'Complete'), ('error', 'Error')], default='recon', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('master_json', models.JSONField(blank=True, null=True)),
                ('report_path', models.CharField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='scanresult',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='scanresult',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='scans.session'),
        ),
    ]
